theme: jekyll-theme-minimal
title: The Workflow Hub project
email: info@esciencelab.org.uk
description: > # this means to ignore newlines until "baseurl:" 
  This website describes the project for developing and running the WorkflowHub, 
  a European-wide registry of scientific workflows. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://about.workflowhub.eu" # the base hostname & protocol for your site
github_username:  workflowhub-eu
encoding: UTF-8
permalink: pretty

logo: logo/worfklowhub.svg
